### PR TITLE
Extend dev dependencies to use symfony 6 and fix deprecation in test

### PR DESCRIPTION
**Pull request by malteschlueter**

### CODE REVIEW

**Comment by mark-gerarts** [comment]
Looks good, thanks for the PR @malteschlueter!

**Comment by tarlepp** [comment]
@mark-gerarts When you've planned to release new tag which contains support for Symfony 6

**Comment by mark-gerarts** [comment]
Sorry for the wait, the new version is available as 1.4.0!

**Comment by tarlepp** [comment]
Awesome, thank you very much!

**Pull request merged**
